trigger:
  branches:
    include:
      - master
      - main

# =========================================================
# SELF-HOSTED AGENT POOL
# =========================================================

pool:
  name: hospital-agent-pool

variables:
- group: sonar-variables

- name: FRONTEND_IMAGE
  value: udayreddychalla/3tier-kubernetes-python-deployement_frontend_repo

- name: BACKEND_IMAGE
  value: udayreddychalla/3tier-kubernetes-python-deployement_backend_repo

- name: TAG
  value: $(Build.BuildId)

stages:

# =========================================================
# STAGE 1 — SONARQUBE CODE SCAN
# =========================================================

- stage: SonarQubeScan
  displayName: SonarQube Code Analysis

  jobs:
    - job: SonarScan

      steps:

        # ============================================
        # INSTALL PYTHON DEPENDENCIES
        # ============================================

        - script: |
            pip3 install -r backend/requirements.txt
          displayName: Install Python Dependencies

        # ============================================
        # RUN SONARQUBE SCAN USING CLI
        # ============================================

        - script: |
            /opt/sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=hospital-management \
              -Dsonar.projectName=hospital-management \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://52.141.58.181:9000 \
              -Dsonar.login=$SONAR_TOKEN
          displayName: Run SonarQube Scan
          env:
            SONAR_TOKEN: $(SONAR_TOKEN)
# =========================================================
# STAGE 2 — BUILD & PUSH FRONTEND IMAGE
# =========================================================

- stage: BuildFrontend
  displayName: Build Frontend Image
  dependsOn: SonarQubeScan

  jobs:
    - job: Frontend

      steps:

        - task: Docker@2
          displayName: Build & Push Frontend Image
          inputs:
            containerRegistry: manoj-docker-connection
            repository: $(FRONTEND_IMAGE)
            command: buildAndPush
            Dockerfile: frontend/Dockerfile
            buildContext: frontend
            tags: |
              $(TAG)
              latest

# =========================================================
# STAGE 3 — BUILD & PUSH BACKEND IMAGE
# =========================================================

- stage: BuildBackend
  displayName: Build Backend Image
  dependsOn: SonarQubeScan

  jobs:
    - job: Backend

      steps:

        - task: Docker@2
          displayName: Build & Push Backend Image
          inputs:
            containerRegistry: manoj-docker-connection
            repository: $(BACKEND_IMAGE)
            command: buildAndPush
            Dockerfile: backend/Dockerfile
            buildContext: backend
            tags: |
              $(TAG)
              latest

# =========================================================
# STAGE 4 — TRIVY SECURITY SCAN
# =========================================================

- stage: TrivySecurityScan
  displayName: Trivy Container Scan
  dependsOn:
    - BuildFrontend
    - BuildBackend

  jobs:
    - job: TrivyScan

      steps:

        - script: |
            docker pull $(FRONTEND_IMAGE):latest
            trivy image \
            --scanners vuln \
            --exit-code 0 \
            --severity CRITICAL,HIGH \
            $(FRONTEND_IMAGE):latest
          displayName: Scan Frontend Image

        - script: |
            docker pull $(BACKEND_IMAGE):latest
            trivy image \
            --scanners vuln \
            --exit-code 0 \
            --severity CRITICAL,HIGH \
            $(BACKEND_IMAGE):latest
          displayName: Scan Backend Image

# =========================================================
# STAGE 5 — DEPLOY TO AKS
# =========================================================

- stage: DeployToAKS
  displayName: Deploy Application to AKS

  dependsOn:
    - TrivySecurityScan

  jobs:
    - job: Deploy

      steps:

        # ============================================
        # VERIFY CLUSTER CONNECTION
        # ============================================

        - script: |
            echo "Checking AKS cluster connection..."

            kubectl get nodes
          displayName: Verify AKS Connection

        # ============================================
        # CREATE NAMESPACE
        # ============================================

        - script: |
            echo "Creating Namespace..."

            kubectl apply -f Kubernetes_yaml_files/namespace.yaml

            echo "Waiting for namespace creation..."

            sleep 10
          displayName: Create Namespace

        # ============================================
        # DEPLOY CONFIGMAP
        # ============================================

        - script: |
            echo "Deploying ConfigMap..."

            kubectl apply -f Kubernetes_yaml_files/configmap.yaml

            kubectl get configmap -n hospital-system
          displayName: Deploy ConfigMap

        # ============================================
        # DEPLOY SECRETS
        # ============================================

        - script: |
            echo "Deploying Secrets..."

            kubectl apply -f Kubernetes_yaml_files/secrets.yaml

            kubectl get secrets -n hospital-system
          displayName: Deploy Secrets

        # ============================================
        # DEPLOY BACKEND
        # ============================================

        - script: |
            echo "Deploying Backend..."

            kubectl apply -f Kubernetes_yaml_files/backend.yaml

            echo "Restarting Backend Deployment..."

            kubectl rollout restart deployment/backend \
            -n hospital-system

            echo "Checking Backend Pods..."

            kubectl get pods -n hospital-system

            echo "Describing Backend Deployment..."

            kubectl describe deployment backend -n hospital-system

            echo "Waiting for Backend Rollout..."

            kubectl rollout status deployment/backend \
            -n hospital-system --timeout=300s

            echo "Backend Deployment Successful"
          displayName: Deploy Backend

        # ============================================
        # DEPLOY FRONTEND
        # ============================================

        - script: |
            echo "Deploying Frontend..."

            kubectl apply -f Kubernetes_yaml_files/frontend.yaml

            echo "Restarting Frontend Deployment..."

            kubectl rollout restart deployment/frontend \
            -n hospital-system

            echo "Checking Frontend Pods..."

            kubectl get pods -n hospital-system

            echo "Describing Frontend Deployment..."

            kubectl describe deployment frontend -n hospital-system

            echo "Describing Frontend Pods..."

            kubectl describe pods -n hospital-system

            echo "Waiting for Frontend Rollout..."

            kubectl rollout status deployment/frontend \
            -n hospital-system --timeout=300s

            echo "Frontend Deployment Successful"
          displayName: Deploy Frontend

        # ============================================
        # DEPLOY NETWORK POLICIES
        # ============================================

        - script: |
            echo "Deploying Network Policies..."

            kubectl apply -f Kubernetes_yaml_files/network-policy.yaml

            kubectl get networkpolicy -n hospital-system
          displayName: Deploy Network Policies

        # ============================================
        # VERIFY ALL RESOURCES
        # ============================================

        - script: |
            echo "Verifying Kubernetes Resources..."

            kubectl get all -n hospital-system

            echo "Checking Services..."

            kubectl get svc -n hospital-system

            echo "Checking HPA..."

            kubectl get hpa -n hospital-system

            echo "Checking Ingress..."

            kubectl get ingress -n hospital-system || true

          displayName: Verify Kubernetes Resources